---
title: "YHR_FlowThrough_June2025"
output: html_document
date: "2025-12-08"
author: "Colin G. Finlay"
---

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = TRUE)
#use to set working directory 
knitr::opts_knit$set(root.dir="~/GitHub/FlowThrough_CoastalAg/analyses")
```

# Packages and data import

```{r load packages}
require("tidyverse")
require("ggpubr")
require("ggtext")
require("xfun")
require("rstatix")
require("NSM3")
```

```{r read in data}
# Fluxes with correct Ar calculation:
Wk1_0730_MIMS_V3 <- read.csv("../data/Calc4_Jan2026/Wk1_730MIMS_TimeCurves.csv")
Wk2_0731_MIMS_V3 <- read.csv("../data/Calc4_Jan2026/Wk2_731MIMS_TimeCurves.csv")

# Teros 12 data from June and December 2025 (coordinates removed):
Teros12 <- read.csv("../data/Teros12_June_Dec_25.csv")
```

# Data wrangling

```{r format date times}
# date times:
Wk1_0730_MIMS_V3$Time <- as.POSIXct(Wk1_0730_MIMS_V3$Time, format = "%m/%d/%y %H:%M")
Wk2_0731_MIMS_V3$Time <- as.POSIXct(Wk2_0731_MIMS_V3$Time, format = "%m/%d/%y %H:%M")
```

```{r split core IDs off of orig.ID}
Wk1_0730_MIMS_V3$CoreID <- substr(Wk1_0730_MIMS_V3$Orig_ID, 1, 3)
Wk2_0731_MIMS_V3$CoreID <- substr(Wk2_0731_MIMS_V3$Orig_ID, 1, 3)
```

# Plotting each timepoint

## µM Ar

```{r µM Ar Week 1 calculation V3}
plot.uM.Ar_Wk1_V3 <- ggplot(data = Wk1_0730_MIMS_V3, aes(x = Time, y = uM_Ar)) +
  facet_grid(~CoreID)+
  geom_line(linewidth = 1) +
  geom_point(size = 4)+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=20),axis.title=element_text(size=20,face="bold"),
          axis.text=element_text(size=20),  
          axis.title.y=element_text(margin=margin(r=10)),
          axis.title.x = element_text(margin = margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 20), legend.position="bottom", legend.title = element_text(size=20), legend.text=element_text(size=20)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "", y = expression(paste("µM Ar")), title="Week 1 (June 9th, 2025)") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA), axis.text.x = element_blank())+
  scale_x_datetime(breaks = "6 hours", limits = as.POSIXct(c("2025-06-11 15:00:00", "2025-06-12 15:00:00")), date_labels = "%m/%d %H:%M")
  
 
plot.uM.Ar_Wk1_V3
```

```{r µM Ar Week 2 calculation V3}
plot.uM.Ar_Wk2_V3 <- ggplot(data = Wk2_0731_MIMS_V3, aes(x = Time, y = uM_Ar)) +
  facet_grid(~CoreID)+
  geom_line(linewidth = 1) +
  geom_point(size = 4)+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=20),axis.title=element_text(size=20,face="bold"),
          axis.text=element_text(size=20),  
          axis.title.y=element_text(margin=margin(r=10)),
          axis.title.x = element_text(margin = margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 20), legend.position="bottom", legend.title = element_text(size=20), legend.text=element_text(size=20)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "", y = expression(paste("µM Ar")), title="Week 2 (June 16th, 2025)") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA), axis.text.x = element_blank())+
  scale_x_datetime(breaks = "6 hours", limits = as.POSIXct(c("2025-06-18 13:00:00", "2025-06-19 13:00:00")), date_labels = "%m/%d %H:%M")
  
 
plot.uM.Ar_Wk2_V3
```

## Ar flux

```{r Ar flux Week 1 calculation V3}
plot.Ar_flux_Wk1_V3 <- ggplot(data = Wk1_0730_MIMS_V3, aes(x = Time, y = Ar_flux_umol_Ar_m.2_hr)) +
  facet_grid(~CoreID)+
  geom_line(linewidth = 1) +
  geom_point(size = 4)+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=20),axis.title=element_text(size=20,face="bold"),
          axis.text=element_text(size=20),  
          axis.title.y=element_text(margin=margin(r=10)),
          axis.title.x = element_text(margin = margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 20), legend.position="bottom", legend.title = element_text(size=20), legend.text=element_text(size=20)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "", y = expression(paste("µMol Ar m"^{-2}, " h"^{-1})), title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA), axis.text.x = element_blank())+
  scale_x_datetime(breaks = "6 hours", limits = as.POSIXct(c("2025-06-11 15:00:00", "2025-06-12 15:00:00")), date_labels = "%m/%d %H:%M")
  
 
plot.Ar_flux_Wk1_V3
```

```{r Ar flux Week 2 calculation V3}
plot.Ar_flux_Wk2_V3 <- ggplot(data = Wk2_0731_MIMS_V3, aes(x = Time, y = Ar_flux_umol_Ar_m.2_hr)) +
  facet_grid(~CoreID)+
  geom_line(linewidth = 1) +
  geom_point(size = 4)+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=20),axis.title=element_text(size=20,face="bold"),
          axis.text=element_text(size=20),  
          axis.title.y=element_text(margin=margin(r=10)),
          axis.title.x = element_text(margin = margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 20), legend.position="bottom", legend.title = element_text(size=20), legend.text=element_text(size=20)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "", y = expression(paste("µMol Ar m"^{-2}, " h"^{-1})), title="") +
  theme(plot.background = element_rect(color=NA), axis.text.x = element_blank())+
  scale_x_datetime(breaks = "6 hours", limits = as.POSIXct(c("2025-06-18 13:00:00", "2025-06-19 13:00:00")), date_labels = "%m/%d %H:%M")
  
 
plot.Ar_flux_Wk2_V3
```

# Flow rate

```{r Flow rate Week 1 calculation V3}
plot.FlowRate_Wk1_V3 <- ggplot(data = Wk1_0730_MIMS_V3, aes(x = Time, y = Flow_L_hr)) +
  facet_grid(~CoreID)+
  geom_line(linewidth = 1) +
  geom_point(size = 4)+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=20),axis.title=element_text(size=20,face="bold"),
          axis.text=element_text(size=20),  
          axis.title.y=element_text(margin=margin(r=10)),
          axis.title.x = element_text(margin = margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 20), legend.position="bottom", legend.title = element_text(size=20), legend.text=element_text(size=20)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "", y = expression(paste("Flow rate (L h"^{-1}, ")")), title="") +
  theme(plot.background = element_rect(color=NA), axis.text.x = element_blank())+
  scale_x_datetime(breaks = "6 hours", limits = as.POSIXct(c("2025-06-11 15:00:00", "2025-06-12 15:00:00")), date_labels = "%m/%d %H:%M")
  
 
plot.FlowRate_Wk1_V3
```

```{r Flow rate Week 2 calculation V3}
plot.FlowRate_Wk2_V3 <- ggplot(data = Wk2_0731_MIMS_V3, aes(x = Time, y = Flow_L_hr)) +
  facet_grid(~CoreID)+
  geom_line(linewidth = 1) +
  geom_point(size = 4)+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=20),axis.title=element_text(size=20,face="bold"),
          axis.text=element_text(size=20),  
          axis.title.y=element_text(margin=margin(r=10)),
          axis.title.x = element_text(margin = margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 20), legend.position="bottom", legend.title = element_text(size=20), legend.text=element_text(size=20)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "", y = expression(paste("Flow rate (L h"^{-1}, ")")), title="") +
  theme(plot.background = element_rect(color=NA), axis.text.x = element_blank())+
  scale_x_datetime(breaks = "6 hours", limits = as.POSIXct(c("2025-06-18 13:00:00", "2025-06-19 13:00:00")), date_labels = "%m/%d %H:%M")
  

plot.FlowRate_Wk2_V3
```

## N2-N flux

```{r N2-N flux Week 1 calculation V3}
plot.N_flux_Wk1_V3 <- ggplot(data = Wk1_0730_MIMS_V3, aes(x = Time, y = N2_flux_umol_N_m.2_hr)) +
  facet_grid(~CoreID)+
  geom_line(linewidth = 1) +
  geom_point(size = 4)+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=20),axis.title=element_text(size=20,face="bold"),
          axis.text=element_text(size=20),  
          axis.title.y=element_text(margin=margin(r=10)),
          axis.title.x = element_text(margin = margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 20), legend.position="bottom", legend.title = element_text(size=20), legend.text=element_text(size=20)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
         labs(x = "", y = expression(paste("µMol N"[2], "-N m"^{-2}, " h"^{-1})), title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA), axis.text.x = element_blank())+
  scale_x_datetime(breaks = "6 hours", limits = as.POSIXct(c("2025-06-11 15:00:00", "2025-06-12 15:00:00")), date_labels = "%m/%d %H:%M")
  
 
plot.N_flux_Wk1_V3
```

```{r N2-N flux Week 2 calculation V3}
plot.N_flux_Wk2_V3 <- ggplot(data = Wk2_0731_MIMS_V3, aes(x = Time, y = N2_flux_umol_N_m.2_hr)) +
  facet_grid(~CoreID)+
  geom_line(linewidth = 1) +
  geom_point(size = 4)+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=20),axis.title=element_text(size=20,face="bold"),
          axis.text=element_text(size=20),  
          axis.title.y=element_text(margin=margin(r=10)),
          axis.title.x = element_text(margin = margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 20), legend.position="bottom", legend.title = element_text(size=20), legend.text=element_text(size=20)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "", y = expression(paste("µMol N"[2], "-N m"^{-2}, " h"^{-1})), title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA), axis.text.x = element_blank())+
  scale_x_datetime(breaks = "6 hours", limits = as.POSIXct(c("2025-06-18 13:00:00", "2025-06-19 13:00:00")), date_labels = "%m/%d %H:%M")
  
 
plot.N_flux_Wk2_V3
```

## O2 flux

```{r O2 flux Week 1 calculation V3}
plot.O2_flux_Wk1_V3 <- ggplot(data = Wk1_0730_MIMS_V3, aes(x = Time, y = O2_flux_umol_O2_m.2_hr)) +
  facet_grid(~CoreID)+
  geom_line(linewidth = 1) +
  geom_point(size = 4)+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=20),axis.title=element_text(size=20,face="bold"),
          axis.text=element_text(size=20),  
          axis.title.y=element_text(margin=margin(r=10)),
          axis.title.x = element_text(margin = margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 20), legend.position="bottom", legend.title = element_text(size=20), legend.text=element_text(size=20)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "", y = expression(paste("µMol O"[2], " m"^{-2}, " h"^{-1})), title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA), axis.text.x = element_text(angle=45, hjust = 1))+
  scale_x_datetime(breaks = "6 hours", limits = as.POSIXct(c("2025-06-11 15:00:00", "2025-06-12 15:00:00")), date_labels = "%m/%d %H:%M")
  
 
plot.O2_flux_Wk1_V3
```

```{r O2 flux Week 2 calculation V3}
plot.O2_flux_Wk2_V3 <- ggplot(data = Wk2_0731_MIMS_V3, aes(x = Time, y = O2_flux_umol_O2_m.2_hr)) +
  facet_grid(~CoreID)+
  geom_line(linewidth = 1) +
  geom_point(size = 4)+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=20),axis.title=element_text(size=20,face="bold"),
          axis.text=element_text(size=20),  
          axis.title.y=element_text(margin=margin(r=10)),
          axis.title.x = element_text(margin = margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 20), legend.position="bottom", legend.title = element_text(size=20), legend.text=element_text(size=20)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
          labs(x = "", y = expression(paste("µMol O"[2], " m"^{-2}, " h"^{-1})), title="") +
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA), axis.text.x = element_text(angle=45, hjust = 1))+
  scale_x_datetime(breaks = "6 hours", limits = as.POSIXct(c("2025-06-18 13:00:00", "2025-06-19 13:00:00")), date_labels = "%m/%d %H:%M")
  
 
plot.O2_flux_Wk2_V3
```

## ggarrange

```{r ggarrange calculation V3}
# Week 1
Wk1_fluxes_comb_V3 <- ggarrange(plotlist = c(plot.uM.Ar_Wk1_V3, plot.Ar_flux_Wk1_V3, plot.FlowRate_Wk1_V3, plot.N_flux_Wk1_V3, plot.O2_flux_Wk1_V3), ncol = 1, nrow = 5, align = "v")

Wk1_fluxes_comb_V3

#ggsave("../figures/Week1_fluxes_V3.png", plot=Wk1_fluxes_comb_V3, device="png", scale=1, width=21, height=20, dpi=600, limitsize=TRUE, bg="white")

# Week 2
Wk2_fluxes_comb_V3 <- ggarrange(plotlist = c(plot.uM.Ar_Wk2_V3, plot.Ar_flux_Wk2_V3, plot.FlowRate_Wk2_V3, plot.N_flux_Wk2_V3, plot.O2_flux_Wk2_V3), ncol = 1, nrow = 5, align = "v")

Wk2_fluxes_comb_V3

#ggsave("../figures/Week2_fluxes_V3.png", plot=Wk2_fluxes_comb_V3, device="png", scale=1, width=21, height=20, dpi=600, limitsize=TRUE, bg="white")
```

# Drop outliers, average time points

```{r}
# Only clear outlier is A05 T1 (Week 1). In this case, both N2 and O2 fluxes are outliers, so we'll drop the entire T1 for A05
Wk1_0730_MIMS_V3 <- Wk1_0730_MIMS_V3 %>%
  filter(Orig_ID != "A05-T1")
```

```{r average the time point for each core}
# Create new data frame with averaged values, Week 1:
Core_Averages_Wk1 <- Wk1_0730_MIMS_V3 %>%
  group_by(CoreID) %>%
  summarise(
    Mean_N2_Flux = mean(N2_flux_umol_N_m.2_hr, na.rm = TRUE),
    Mean_O2_Flux = mean(O2_flux_umol_O2_m.2_hr, na.rm = TRUE)
  )

# Create new data frame with averaged values, Week 2:
Core_Averages_Wk2 <- Wk2_0731_MIMS_V3 %>%
  group_by(CoreID) %>%
  summarise(
    Mean_N2_Flux = mean(N2_flux_umol_N_m.2_hr, na.rm = TRUE),
    Mean_O2_Flux = mean(O2_flux_umol_O2_m.2_hr, na.rm = TRUE)
  )
```

```{r Add week labels, combine DFs, add site labels}
# Week 1 (June 9th, 2025)
Core_Averages_Wk1$Week <- "9-June-2025"
# Week 2 (June 16th, 2025)
Core_Averages_Wk2$Week <- "16-June-2025"

# Combine data frames
Core_Averages <- bind_rows(Core_Averages_Wk1, Core_Averages_Wk2)

# Add site labels (A, B, C)
Core_Averages <- Core_Averages %>%
  mutate(Plot = substr(CoreID, 1, 1))

# Add flood risk labels
Core_Averages <- Core_Averages %>%
  mutate(Flood = case_when(
    Plot == "A" ~ "Regulatory floodway",
    Plot == "B" ~ "1% Annual chance",
    Plot == "C" ~ "0.2% Annual chance",
    TRUE ~ NA_character_ # Optional: sets anything else to NA
  ))
```

```{r set factors}
Core_Averages$Plot <- as.factor(Core_Averages$Plot)

Core_Averages$Week <- factor(Core_Averages$Week, levels = c("9-June-2025", "16-June-2025"))
```

# Stats assumptions

```{r basic stat assumptions for single timepoint of flux data}
# Shapiro tests
  # N2 flux
Core_Averages_Wk1 %>%
  shapiro_test(Mean_N2_Flux)
  # Accept null: normally distributed

  # O2 flux
Core_Averages_Wk1 %>%
  shapiro_test(Mean_O2_Flux)
  # Accept null: normally distributed

# QQ plots
  # N2 flux
ggqqplot(Core_Averages_Wk1, "Mean_N2_Flux") # Acceptable

  # O2 flux
ggqqplot(Core_Averages_Wk1, "Mean_O2_Flux") # Acceptable
```

# Plotting average fluxes and Teros 12 data

## Plotting both weeks

```{r N2-N flux both weeks}
# Plotting:
plot.N2_Wk1_Wk2 <- ggplot(Core_Averages, aes(x=Plot, y=Mean_N2_Flux)) +
  facet_wrap(vars(as.factor(Week)), nrow = 1, ncol = 2)+
                    geom_boxplot(aes(color=Plot), outlier.shape = NA) +
                    geom_point(aes(color=Plot), size = 2, position = position_jitterdodge()) +
  scale_color_manual(values=c("#86a8d2","#9c509f","#a88ec0"), labels = c("A: Regulatory Floodway", "B: 1% Annual Chance", "C: 0.2% Annual Chance"), name="Flood Hazard")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=10), axis.title=element_text(size=10,face="bold"),
          axis.text=element_text(size=10, color = "black"),
          axis.text.x = element_text(angle = 0),panel.border = element_rect(colour = "black",size=1),strip.text = element_text(size = 10), legend.position="right", legend.title = element_text(size=10), legend.text=element_text(size=10)) + 
theme(axis.ticks.length = unit(0.3, "cm"), axis.title.y = element_markdown()) + 
  labs(x = "Flood Hazard", 
    # Use standard markdown (**) for bold and HTML (<sup>) for superscripts
    y = "**µmol N<sub>2</sub>-N m<sup>-2</sup> h<sup>-1</sup>**", title = "")
 
plot.N2_Wk1_Wk2

#ggsave("../figures/Ecosphere_pub/iris_tubes.tiff", plot=plot.IRIS_nested, device="tiff", path=NULL, scale=1, width= 18, height= 22, units = "cm", dpi=600, limitsize=TRUE, bg="white")
```

```{r O2 flux both weeks}
# Plotting:
plot.O2_Wk1_Wk2 <- ggplot(Core_Averages, aes(x=Plot, y=Mean_O2_Flux)) +
  facet_wrap(vars(as.factor(Week)), nrow = 1, ncol = 2)+
                    geom_boxplot(aes(color=Plot), outlier.shape = NA) +
                    geom_point(aes(color=Plot), size = 2, position = position_jitterdodge()) +
  scale_color_manual(values=c("#86a8d2","#9c509f","#a88ec0"), labels = c("A: Regulatory Floodway", "B: 1% Annual Chance", "C: 0.2% Annual Chance"), name="Flood Hazard")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=10), axis.title=element_text(size=10,face="bold"),
          axis.text=element_text(size=10, color = "black"),
          axis.text.x = element_text(angle = 0),panel.border = element_rect(colour = "black",size=1),strip.text = element_text(size = 10), legend.position="right", legend.title = element_text(size=10), legend.text=element_text(size=10)) + 
theme(axis.ticks.length = unit(0.3, "cm"), axis.title.y = element_markdown()) + 
  labs(x = "Flood Hazard", 
    # Use standard markdown (**) for bold and HTML (<sup>) for superscripts
    y = "**µmol O<sub>2</sub> m<sup>-2</sup> h<sup>-1</sup>**", title = "")
 
plot.O2_Wk1_Wk2

#ggsave("../figures/Ecosphere_pub/iris_tubes.tiff", plot=plot.IRIS_nested, device="tiff", path=NULL, scale=1, width= 18, height= 22, units = "cm", dpi=600, limitsize=TRUE, bg="white")
```

## Plotting Week 1 only

```{r drop Week 2}
# remove Week 2 from Core_Averages
Core_Averages_Wk1 <- Core_Averages %>%
  filter(Week == "9-June-2025")
```

```{r N2-N flux week 1}
# Plotting:
plot.N2_Wk1 <- ggplot(Core_Averages_Wk1, aes(x=Plot, y=Mean_N2_Flux)) +
                    geom_boxplot(aes(color=Plot), outlier.shape = NA) +
                    geom_point(aes(color=Plot), size = 2, position = position_jitterdodge()) +
  scale_color_manual(values=c("#86a8d2","#9c509f"), labels = c("A: Regulatory Floodway", "B: 1% Annual Chance"), name="Flood Hazard")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=10), axis.title=element_text(size=10,face="bold"),
          axis.text=element_text(size=10, color = "black"),
          axis.text.x = element_text(), panel.border = element_rect(colour = "black",size=1),strip.text = element_text(size = 10), legend.position="right", legend.title = element_text(size=10), legend.text=element_text(size=10)) + 
theme(axis.ticks.length = unit(0.3, "cm"), axis.title.y = element_markdown()) + 
  labs(x = "", 
    # Use standard markdown (**) for bold and HTML (<sup>) for superscripts
    y = "**µmol N<sub>2</sub>-N m<sup>-2</sup> h<sup>-1</sup>**", title = "")
 
plot.N2_Wk1

#ggsave("../figures/Ecosphere_pub/iris_tubes.tiff", plot=plot.IRIS_nested, device="tiff", path=NULL, scale=1, width= 18, height= 22, units = "cm", dpi=600, limitsize=TRUE, bg="white")
```

```{r T test on Week 1 N2 fluxes}
# Define the single pair you want to compare
my_comparisons <- list( c("A", "B") )

plot.N2_Wk1_Ttest <- ggplot(Core_Averages_Wk1, aes(x=Plot, y=Mean_N2_Flux)) +
  geom_boxplot(aes(color=Plot), outlier.shape = NA) +
  geom_point(aes(color=Plot), size = 2, position = position_jitterdodge()) +
  scale_color_manual(
    values=c("#86a8d2","#9c509f"), 
    labels = c("A: Regulatory Floodway", "B: 1% Annual Chance"), 
    name="Flood Hazard"
  ) +
  
  # ADDED: Unpaired T-test for the two groups
  stat_compare_means(
    comparisons = my_comparisons,
    method = "t.test",
    paired = FALSE,
    label = "p.signif" # Change to "p.signif" if you prefer *, **, ***,
  ) +
  
  theme_bw() +
  # Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  # Set axis title and text properties, tick marks, and labels
  theme(
    text=element_text(size=10), 
    axis.title=element_text(size=10,face="bold"),
    axis.text=element_text(size=10, color = "black"),
    axis.text.x = element_text(), 
    panel.border = element_rect(colour = "black",size=1),
    strip.text = element_text(size = 10), 
    legend.position="right", 
    legend.title = element_text(size=10), 
    legend.text=element_text(size=10)
  ) + 
  theme(
    axis.ticks.length = unit(0.3, "cm"), 
    axis.title.y = element_markdown()
  ) + 
  labs(
    x = "", 
    y = "**µmol N<sub>2</sub>-N m<sup>-2</sup> h<sup>-1</sup>**", 
    title = ""
  )

plot.N2_Wk1_Ttest
```

```{r O2 flux week 1}
# Plotting:
plot.O2_Wk1 <- ggplot(Core_Averages_Wk1, aes(x=Plot, y=Mean_O2_Flux)) +
                    geom_boxplot(aes(color=Plot), outlier.shape = NA) +
                    geom_point(aes(color=Plot), size = 2, position = position_jitterdodge()) +
  scale_color_manual(values=c("#86a8d2","#9c509f"), labels = c("A: Regulatory Floodway", "B: 1% Annual Chance"), name="Flood Hazard")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=10), axis.title=element_text(size=10,face="bold"),
          axis.text=element_text(size=10, color = "black"),
          axis.text.x = element_text(angle = 0),panel.border = element_rect(colour = "black",size=1),strip.text = element_text(size = 10), legend.position="right", legend.title = element_text(size=10), legend.text=element_text(size=10)) + 
theme(axis.ticks.length = unit(0.3, "cm"), axis.title.y = element_markdown()) + 
  labs(x = "Flood Hazard", 
    # Use standard markdown (**) for bold and HTML (<sup>) for superscripts
    y = "**µmol O<sub>2</sub> m<sup>-2</sup> h<sup>-1</sup>**", title = "")
 
plot.O2_Wk1

#ggsave("../figures/Ecosphere_pub/iris_tubes.tiff", plot=plot.IRIS_nested, device="tiff", path=NULL, scale=1, width= 18, height= 22, units = "cm", dpi=600, limitsize=TRUE, bg="white")
```

```{r T test on Week 1 O2 fluxes}
plot.O2_Wk1_Ttest <- ggplot(Core_Averages_Wk1, aes(x=Plot, y=Mean_O2_Flux)) +
  geom_boxplot(aes(color=Plot), outlier.shape = NA) +
  geom_point(aes(color=Plot), size = 2, position = position_jitterdodge()) +
  scale_color_manual(
    values=c("#86a8d2","#9c509f"), 
    labels = c("A: Regulatory Floodway", "B: 1% Annual Chance"), 
    name="Flood Hazard"
  ) +
  
  # ADDED: Unpaired T-test for the two groups
  stat_compare_means(
    comparisons = my_comparisons,
    method = "t.test",
    paired = FALSE,
    label = "p.signif" # Change to "p.signif" if you prefer *, **, ***,
  ) +
  
  theme_bw() +
  # Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  # Set axis title and text properties, tick marks, and labels
  theme(
    text=element_text(size=10), 
    axis.title=element_text(size=10,face="bold"),
    axis.text=element_text(size=10, color = "black"),
    axis.text.x = element_text(), 
    panel.border = element_rect(colour = "black",size=1),
    strip.text = element_text(size = 10), 
    legend.position="right", 
    legend.title = element_text(size=10), 
    legend.text=element_text(size=10)
  ) + 
  theme(
    axis.ticks.length = unit(0.3, "cm"), 
    axis.title.y = element_markdown()
  ) + 
  labs(
    x = "", 
    y = "**µmol O<sub>2</sub>-N m<sup>-2</sup> h<sup>-1</sup>**", 
    title = ""
  )

plot.O2_Wk1_Ttest
```

```{r ggarrange}
Wk1_N2_O2_flux <- ggarrange(plot.N2_Wk1, plot.O2_Wk1, labels = c("(a)", "(b)"), ncol = 1, nrow = 2, legend = "right", common.legend = T, align = "hv")

Wk1_N2_O2_flux

#ggsave("../figures/Wk1_N2_O2_flux.png", plot=Wk1_N2_O2_flux, device="png", path=NULL, scale=1, width=18, height=22, units = "cm", dpi=600, limitsize=TRUE, bg="white")
```

# Teros 12 data

```{r nicer date labels for plot}
# change format to e.g., 9-Jun
# factor and order so 9-Jun comes before 16-Dec

Teros12 <- Teros12 %>%
  mutate(
    # 1. Convert the string to a real Date object
    real_date = mdy(Date_sampled), 
    
    # 2. Format to "Jun 9" (trimws removes the extra space %e leaves behind)
    Date_format = trimws(format(real_date, "%b %e")), 
    
    # 3. Make it a factor and automatically order it by the actual calendar date
    Date_format = fct_reorder(Date_format, real_date) 
  ) %>%
  select(-real_date) # Drop the temporary date column
```

## Teros 12 stats

### Stat assumptions on residuals

```{r stats: moisture}
# 1. Fit models by group and extract residuals into a new column
Teros12 <- Teros12 %>%
  # Group by your date factor
  group_by(Date_format) %>%
  # Fit the model for each group and extract residuals
  mutate(
    model_residuals = residuals(lm(Moisture_m3_m3 ~ Sampling_Zone, data = pick(everything())))
  ) %>%
  ungroup()

# 2. Run the Shapiro-Wilk test on the new residuals column per date
tapply(Teros12$model_residuals, Teros12$Date_format, shapiro.test)

# 3. Plot the residuals using ggplot2
ggplot(Teros12, aes(sample = model_residuals)) +
  stat_qq() +
  stat_qq_line(color = "red") +
  facet_wrap(~ Date_format) +
  theme_minimal() +
  labs(
    title = "QQ Plots of Model Residuals by Sampling Date",
    subtitle = "Model: Moisture ~ Sampling_Zone"
  )

# June 9: Not normal
# December 16: Normal
```

```{r stats: temperature}
# 1. Fit models by group and extract residuals into a new column
Teros12 <- Teros12 %>%
  # Group by your date factor
  group_by(Date_format) %>%
  # Fit the model for each group and extract residuals
  mutate(
    model_residuals = residuals(lm(Temperature_degC ~ Sampling_Zone, data = pick(everything())))
  ) %>%
  ungroup()

# 2. Run the Shapiro-Wilk test on the new residuals column per date
tapply(Teros12$model_residuals, Teros12$Date_format, shapiro.test)

# 3. Plot the residuals using ggplot2
ggplot(Teros12, aes(sample = model_residuals)) +
  stat_qq() +
  stat_qq_line(color = "red") +
  facet_wrap(~ Date_format) +
  theme_minimal() +
  labs(
    title = "QQ Plots of Model Residuals by Sampling Date",
    subtitle = "Model: Temperature ~ Sampling_Zone"
  )

# June 9: Not normal
# December 16: Not normal
```

```{r stats: conductivity}
# 1. Fit models by group and extract residuals into a new column
Teros12 <- Teros12 %>%
  # Group by your date factor
  group_by(Date_format) %>%
  # Fit the model for each group and extract residuals
  mutate(
    model_residuals = residuals(lm(Conductivity_mS_cm ~ Sampling_Zone, data = pick(everything())))
  ) %>%
  ungroup()

# 2. Run the Shapiro-Wilk test on the new residuals column per date
tapply(Teros12$model_residuals, Teros12$Date_format, shapiro.test)

# 3. Plot the residuals using ggplot2
ggplot(Teros12, aes(sample = model_residuals)) +
  stat_qq() +
  stat_qq_line(color = "red") +
  facet_wrap(~ Date_format) +
  theme_minimal() +
  labs(
    title = "QQ Plots of Model Residuals by Sampling Date",
    subtitle = "Model: Conductivity ~ Sampling_Zone"
  )

# June 9: Not normal
# December 16: Normal
```

## Teros 12 plots

### Moisture

#### Stats

```{r set factors}
# Sampling zone (plot)
Teros12$Sampling_Zone <- as.factor(Teros12$Sampling_Zone)
```

##### June 9, 2025

```{r Kruskal-Wallis}
kruskal_Moist_Jun9 <- kruskal.test(data = Teros12, Moisture_m3_m3 ~ Sampling_Zone, subset = Date_format == "Jun  9")

kruskal_Moist_Jun9
```

```{r SDCFlig}
# Subset by date
Teros12_Jun9 <- Teros12 %>% filter(Date_format == "Jun  9")

# set random seed
set.seed(42)

# Pairwise comparisons
SDCFlig_Moist_Jun9 <- pSDCFlig(x = Teros12_Jun9$Moisture_m3_m3, g = Teros12_Jun9$Sampling_Zone, method = "Monte Carlo", n.mc = 10000)

SDCFlig_Moist_Jun9
```

##### December 16, 2025

```{r}
# ANOVA with Tukey's HSD (see G. chat from 3/30/26)
```

#### Plotting

```{r Teros 12 plot: moisture}
# Plotting:
plot.moisture <- ggplot(Teros12, aes(x=Sampling_Zone, y=Moisture_m3_m3)) +
  facet_wrap(vars(as.factor(Date_format)), nrow = 1, ncol = 2)+
                    geom_boxplot(aes(color=Sampling_Zone), outlier.shape = NA) +
                    geom_point(aes(color=Sampling_Zone), size = 2, position = position_jitterdodge()) +
  scale_color_manual(values=c("#86a8d2","#9c509f","#a88ec0"), labels = c("A: Regulatory Floodway", "B: 1% Annual Chance", "C: 0.2% Annual Chance"), name="Flood Hazard")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=10), axis.title=element_text(size=10,face="bold"),
          axis.text=element_text(size=10, color = "black"),
          axis.text.x = element_text(angle = 0),panel.border = element_rect(colour = "black",size=1),strip.text = element_text(size = 10), legend.position="right", legend.title = element_text(size=10), legend.text=element_text(size=10)) + 
theme(axis.ticks.length = unit(0.3, "cm"), axis.title.y = element_markdown()) + 
  labs(x = "Flood Hazard", 
    # Use standard markdown (**) for bold and HTML (<sup>) for superscripts
    y = "**Moisture (m<sup>3</sup> m<sup>-3</sup>)**", title = "")
 
plot.moisture
```

```{r Teros 12 plot: Temperature}
# Plotting:
plot.temp <- ggplot(Teros12, aes(x=Sampling_Zone, y=Temperature_degC)) +
  facet_wrap(vars(as.factor(Date_format)), nrow = 1, ncol = 2)+
                    geom_boxplot(aes(color=Sampling_Zone), outlier.shape = NA) +
                    geom_point(aes(color=Sampling_Zone), size = 2, position = position_jitterdodge()) +
  scale_color_manual(values=c("#86a8d2","#9c509f","#a88ec0"), labels = c("A: Regulatory Floodway", "B: 1% Annual Chance", "C: 0.2% Annual Chance"), name="Flood Hazard")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=10), axis.title=element_text(size=10,face="bold"),
          axis.text=element_text(size=10, color = "black"),
          axis.text.x = element_text(angle = 0),panel.border = element_rect(colour = "black",size=1),strip.text = element_text(size = 10), legend.position="right", legend.title = element_text(size=10), legend.text=element_text(size=10)) + 
theme(axis.ticks.length = unit(0.3, "cm"), axis.title.y = element_markdown()) + 
  labs(x = "Flood Hazard", 
    # Use standard markdown (**) for bold and HTML (<sup>) for superscripts
    y = "**Temperature (° C)**", title = "")
 
plot.temp
```

```{r Teros 12 plot: Conductivity}
# Plotting:
plot.cond <- ggplot(Teros12, aes(x=Sampling_Zone, y=Conductivity_mS_cm)) +
  facet_wrap(vars(as.factor(Date_format)), nrow = 1, ncol = 2)+
                    geom_boxplot(aes(color=Sampling_Zone), outlier.shape = NA) +
                    geom_point(aes(color=Sampling_Zone), size = 2, position = position_jitterdodge()) +
  scale_color_manual(values=c("#86a8d2","#9c509f","#a88ec0"), labels = c("A: Regulatory Floodway", "B: 1% Annual Chance", "C: 0.2% Annual Chance"), name="Flood Hazard")+
  theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=10), axis.title=element_text(size=10,face="bold"),
          axis.text=element_text(size=10, color = "black"),
          axis.text.x = element_text(angle = 0),panel.border = element_rect(colour = "black",size=1),strip.text = element_text(size = 10), legend.position="right", legend.title = element_text(size=10), legend.text=element_text(size=10)) + 
theme(axis.ticks.length = unit(0.3, "cm"), axis.title.y = element_markdown()) + 
  labs(x = "Flood Hazard", 
    # Use standard markdown (**) for bold and HTML (<sup>) for superscripts
    y = "**Conductivity (mS cm<sup>-1</sup>)**", title = "")
 
plot.cond
```



